#!/bin/sh

RED="\e[31m"
CYAN="\e[36m"

DIM="\e[2m"
RESET="\e[0m"
BOLD="\e[1m"
UNDERLINE="\e[4m"

########################################################

printMsg () {
	echo -e "$1${RESET}"
}

printHelp () {
	printMsg "Welcome to bGit, a simpler git interface. You are running bGit ${CYAN}0.1" 

	printMsg ""
	printMsg "Here's the list of commands:"
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Information commands"
	printMsg "    ${CYAN}bgit helper"
	printMsg "        Runs the ${CYAN}bgit helper${RESET}. This helps identify any"
	printMsg "        issues with the state of the repository and advises you on"
	printMsg "        what you can do next if you get stuck."
	printMsg ""
	printMsg "    ${CYAN}bgit info"
	printMsg "        Display the current working state. This will display"
	printMsg "        information on what branch you're in, what actions"
	printMsg "        are available and what you can do."
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Main commands"
	printMsg "    ${CYAN}bgit init"
	printMsg "        Sets up a default repository, and initializes bgit for use."
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Branch commands"
	printMsg "    ${CYAN}bgit goto <branch>"
	printMsg "        Goes to a certain branch. This will create a new branch if"
	printMsg "        it doesn't already exist"
	printMsg ""
	printMsg "    ${CYAN}bgit ${RED}prune ${CYAN}<branch>"
	printMsg "        Destroys a branch. ${RED}This action cannot be reversed!"
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Dangerous commands"
	printMsg "    ${BOLD}${RED}bgit destroy"
	printMsg "        Destroys the entire ${CYAN}.bgit${RESET} folder. This does not delete any"
	printMsg "        other files in this directory, but will destroy all information"
	printMsg "        that bgit has about this repository. ${RED}This action cannot be reversed!"
	echo ""
}

########################################################

doHelper () {
	printMsg "Hi, I'm the ${CYAN}bgit helper${RESET}. Let's try and resolve"
	printMsg "your problem!"
	if [ -d ".bgit" ]; then
		:
	else 
		printMsg ""
		printMsg "${DIM}----------------------------------------------"
		printMsg "${DIM}Hey, you haven't set up a repository here yet."
		printMsg "${DIM}Try using ${CYAN}bgit init${RESET}${DIM} to get started!"
		printMsg "${DIM}----------------------------------------------"
	fi
	printMsg ""
}

########################################################

askForConfirmation () {
	printf "Are you sure you want me to make these changes? [y/n] "
	read -n 1 input
	echo ""
	if [ "$input" == "y" ] || [ "$input" == "Y" ]; then
		return 0 # Success
	else 
		return 1 # Error
	fi
}

doInit () {
	if [ -d ".bgit" ]; then
		:
	else 
		printMsg "I'm planning on setting up a new repository."
		printMsg "This will create a ${CYAN}.bgit${RESET} folder in your current directory."
		printMsg ""

		askForConfirmation
		if [ $? -eq 0 ]; then
			mkdir ".bgit"
			printMsg "I've created the ${CYAN}.bgit${RESET} directory for you."
		else 
			printMsg "Sure thing, I've made no changes."
		fi
	fi
}

########################################################

doGoto() {
	:
}

########################################################

case $1 in
	help)
		printHelp;;

	helper)
		doHelper;;

	init)
		doInit;;

	goto)
		doGoto $2;;

	test)
		;;
	*)
		echo "Type 'bgit help' for help" ;;
esac 
