#!/bin/sh

VERSION="0.1"

# Formatting & Colors

RED="\e[31m"
CYAN="\e[36m"

DIM="\e[2m"
RESET="\e[0m"
BOLD="\e[1m"
UNDERLINE="\e[4m"

### General helper functions ###########################

stringContains() {
	if [[ $1 == *$2* ]]; then
		return 0 # Success
	else 
		return 1 # Error
	fi
}

### Variables ##########################################

branches=""
currentBranch=""

### Git helper commands ################################

getCurrentBranch() {
	currentBranch="$(git symbolic-ref HEAD | cut -d/ -f3-)"
}

getBranches() {
	branches="$(git for-each-ref refs/heads --format="%(refname)" | cut -d/ -f3- | tr '\n' ' ' | awk '{$1=$1};1')"
}

### Help printing ######################################

printMsg () {
	echo -e "$1${RESET}"
}

printHelp () {
	printMsg "Welcome to bGit, a simpler git interface. You are running bGit ${CYAN}${VERSION}" 

	printMsg ""
	printMsg "Here's the list of commands:"
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Information commands"
	printMsg "    ${CYAN}bgit helper"
	printMsg "        Runs the ${CYAN}bgit helper${RESET}. This helps identify any"
	printMsg "        issues with the state of the repository and advises you on"
	printMsg "        what you can do next if you get stuck."
	printMsg ""
	printMsg "    ${CYAN}bgit info"
	printMsg "        Display the current working state. This will display"
	printMsg "        information on what branch you're in, what actions"
	printMsg "        are available and what you can do."
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Main commands"
	printMsg "    ${CYAN}bgit init"
	printMsg "        Sets up a default repository, and initializes bgit for use."
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Branch commands"
	printMsg "    ${CYAN}bgit goto <branch>"
	printMsg "        Goes to a certain branch. This will create a new branch if"
	printMsg "        it doesn't already exist"
	printMsg ""
	printMsg "    ${CYAN}bgit protect <branch>"
	printMsg "        Prevents a branch from being deleted"
	printMsg ""
	printMsg "    ${CYAN}bgit ${RED}prune ${CYAN}<branch>"
	printMsg "        Destroys a branch. ${RED}This action cannot be reversed!"
	printMsg ""
	printMsg "    ${UNDERLINE}${DIM}Dangerous commands"
	printMsg "    ${BOLD}${RED}bgit destroy"
	printMsg "        Destroys the entire ${CYAN}.bgit${RESET} folder. This does not delete any"
	printMsg "        other files in this directory, but will destroy all information"
	printMsg "        that bgit has about this repository. ${RED}This action cannot be reversed!"
	echo ""
}

########################################################

doHelper () {
	printMsg "Hi, I'm the ${CYAN}bgit helper${RESET}. Let's try and resolve"
	printMsg "your problem!"
	if [ -d ".bgit" ]; then
		:
	else 
		printMsg ""
		printMsg "${DIM}----------------------------------------------"
		printMsg "${DIM}Hey, you haven't set up a repository here yet."
		printMsg "${DIM}Try using ${CYAN}bgit init${RESET}${DIM} to get started!"
		printMsg "${DIM}----------------------------------------------"
	fi
	printMsg ""
}

########################################################

askForConfirmation () {
	printf "Are you sure you want me to make these changes? [y/n] "
	read -n 1 input
	echo ""
	if [ "$input" == "y" ] || [ "$input" == "Y" ]; then
		return 0 # Success
	else 
		return 1 # Error
	fi
}

doInit () {
	if [ -d ".bgit" ]; then
		:
	else 
		printMsg "I'm planning on setting up a new repository."
		printMsg "This will create a ${CYAN}.bgit${RESET} folder in your current directory."
		printMsg ""

		askForConfirmation
		if [ $? -eq 0 ]; then
			mkdir ".bgit"
			printMsg "I've created the ${CYAN}.bgit${RESET} directory for you."
		else 
			printMsg "Sure thing, I've made no changes."
		fi
	fi
}

########################################################

doGoto() {
	targetBranch=$1

	getCurrentBranch
	if [ "$targetBranch" = "$currentBranch" ]; then
		echo "You're already in $targetBranch!"
		return
	fi

	getBranches 

	# echo "'$branches'"
	# echo $targetBranch

	stringContains $branches $targetBranch
	if [ $? -eq 0 ]; then
		echo "yes"
	else
		printMsg "I'm planning on creating a new branch called ${CYAN}$targetBranch${RESET}."
		askForConfirmation
		if [ $? -eq 0 ]; then
			git checkout -qb $targetBranch
			printMsg "I've created the branch ${CYAN}$targetBranch${RESET} for you. You are currently in ${CYAN}$targetBranch${RESET}."
		else 
			printMsg "I've not made the branch ${CYAN}$targetBranch${RESET}. You are currently in ${CYAN}$currentBranch${RESET}."
		fi
	fi
}

########################################################

case $1 in
	help)
		printHelp;;

	helper)
		doHelper;;

	init)
		doInit;;

	goto)
		doGoto $2;;

	test)
		getBranches
		for branch in $branches; do
			echo "$branch <-<"
		done



		stringContains "hello" "lo"
		if [ $? -eq 0 ]; then
			echo "yes"
		else
			echo "no"
		fi
		;;
	*)
		echo "Type 'bgit help' for help" ;;
esac 
